export { default as Login } from './Login';
export { default as SignUp } from './SignUp';
export { default as Error } from './Error';
export { default as Main } from './Main';
export { default as MyPage } from './MyPage';
export { default as Category } from './Category';
export { default as PwEdit } from './PasswordEdit';
export { default as PostDetail } from './PostDetail';
export { default as Write } from './Write';
export { default as CategoryWrite } from './CategoryWrite'